### PR TITLE
RELATED: FET-564 Add sonar config

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- react-dnd-touch-backend-fossa-scanning-oss-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/react-dnd-touch-backend-merge-compliance-check/1/ : FAILURE in 0s

**Comment by pbenes** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/react-dnd-touch-backend-fossa-scanning-oss-zuul-el7/1/ : SUCCESS in 2m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/react-dnd-touch-backend-merge-compliance-check/2/ : SUCCESS in 27s

**Pull request merged**
